-- Create authors table
CREATE TABLE authors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  bio text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create themes table
CREATE TABLE themes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  slug varchar(255) NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create poems table
CREATE TABLE poems (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id bigint REFERENCES authors(id) ON DELETE CASCADE,
  theme_id bigint REFERENCES themes(id) ON DELETE RESTRICT,
  title varchar(255) NOT NULL,
  slug varchar(255) NOT NULL UNIQUE,
  content text NOT NULL,
  is_winner boolean DEFAULT false,
  rank smallint,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create sponsors table
CREATE TABLE sponsors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  logo_url varchar(255),
  website_url varchar(255),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optional: Enable Row Level Security (RLS) and add policies
ALTER TABLE authors ENABLE ROW LEVEL SECURITY;
ALTER TABLE themes ENABLE ROW LEVEL SECURITY;
ALTER TABLE poems ENABLE ROW LEVEL SECURITY;
ALTER TABLE sponsors ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access to authors" ON authors FOR SELECT USING (true);
CREATE POLICY "Allow public read access to themes" ON themes FOR SELECT USING (true);
CREATE POLICY "Allow public read access to poems" ON poems FOR SELECT USING (true);
CREATE POLICY "Allow public read access to sponsors" ON sponsors FOR SELECT USING (true);

-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Add triggers to update 'updated_at' automatically
CREATE TRIGGER update_authors_modtime BEFORE UPDATE ON authors FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
CREATE TRIGGER update_themes_modtime BEFORE UPDATE ON themes FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
CREATE TRIGGER update_poems_modtime BEFORE UPDATE ON poems FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
CREATE TRIGGER update_sponsors_modtime BEFORE UPDATE ON sponsors FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
